<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/cotars_game_proto_card.proto

namespace Cotars\GameProtoCard;

/**
 * Protobuf type <code>Cotars.GameProtoCard.CARD_TYPE</code>
 */
class CARD_TYPE
{
    /**
     * Generated from protobuf enum <code>CARD_TYPE_SPADE = 0;</code>
     */
    const CARD_TYPE_SPADE = 0;
    /**
     * Generated from protobuf enum <code>CARD_TYPE_HEART = 1;</code>
     */
    const CARD_TYPE_HEART = 1;
    /**
     * Generated from protobuf enum <code>CARD_TYPE_DIAMOND = 2;</code>
     */
    const CARD_TYPE_DIAMOND = 2;
    /**
     * Generated from protobuf enum <code>CARD_TYPE_CLUB = 3;</code>
     */
    const CARD_TYPE_CLUB = 3;
    /**
     * Generated from protobuf enum <code>CARD_TYPE_KING = 4;</code>
     */
    const CARD_TYPE_KING = 4;
}

