<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/cotars_game_proto_card.proto

namespace Cotars\GameProtoCard;

/**
 * Protobuf type <code>Cotars.GameProtoCard.GameStatus</code>
 */
class GameStatus
{
    /**
     * Generated from protobuf enum <code>GAME_STATUS_IDLE = 0;</code>
     */
    const GAME_STATUS_IDLE = 0;
    /**
     * Generated from protobuf enum <code>GAME_STATUS_READY = 1;</code>
     */
    const GAME_STATUS_READY = 1;
    /**
     * Generated from protobuf enum <code>GAME_STATUS_START = 2;</code>
     */
    const GAME_STATUS_START = 2;
}

