<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/cotars_game_proto_card.proto

namespace Cotars\GameProtoCard;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Cotars.GameProtoCard.GameActionReq</code>
 */
class GameActionReq extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 tableid = 1;</code>
     */
    private $tableid = 0;
    /**
     * Generated from protobuf field <code>uint32 seatid = 2;</code>
     */
    private $seatid = 0;
    /**
     * Generated from protobuf field <code>repeated uint32 action = 3;</code>
     */
    private $action;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $tableid
     *     @type int $seatid
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $action
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\CotarsGameProtoCard::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 tableid = 1;</code>
     * @return int
     */
    public function getTableid()
    {
        return $this->tableid;
    }

    /**
     * Generated from protobuf field <code>uint32 tableid = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setTableid($var)
    {
        GPBUtil::checkUint32($var);
        $this->tableid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 seatid = 2;</code>
     * @return int
     */
    public function getSeatid()
    {
        return $this->seatid;
    }

    /**
     * Generated from protobuf field <code>uint32 seatid = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setSeatid($var)
    {
        GPBUtil::checkUint32($var);
        $this->seatid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 action = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAction()
    {
        return $this->action;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 action = 3;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAction($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->action = $arr;

        return $this;
    }

}

