<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/cotars_game_proto_card.proto

namespace Cotars\GameProtoCard;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Cotars.GameProtoCard.GameCardMoveNtf</code>
 */
class GameCardMoveNtf extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 tableid = 1;</code>
     */
    private $tableid = 0;
    /**
     * Generated from protobuf field <code>uint32 fromSeatid = 2;</code>
     */
    private $fromSeatid = 0;
    /**
     * Generated from protobuf field <code>uint32 toSeatid = 3;</code>
     */
    private $toSeatid = 0;
    /**
     * Generated from protobuf field <code>uint32 areaid = 4;</code>
     */
    private $areaid = 0;
    /**
     * Generated from protobuf field <code>uint32 action = 5;</code>
     */
    private $action = 0;
    /**
     * Generated from protobuf field <code>uint32 count = 6;</code>
     */
    private $count = 0;
    /**
     * Generated from protobuf field <code>repeated uint32 cards = 7;</code>
     */
    private $cards;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $tableid
     *     @type int $fromSeatid
     *     @type int $toSeatid
     *     @type int $areaid
     *     @type int $action
     *     @type int $count
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $cards
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\CotarsGameProtoCard::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 tableid = 1;</code>
     * @return int
     */
    public function getTableid()
    {
        return $this->tableid;
    }

    /**
     * Generated from protobuf field <code>uint32 tableid = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setTableid($var)
    {
        GPBUtil::checkUint32($var);
        $this->tableid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 fromSeatid = 2;</code>
     * @return int
     */
    public function getFromSeatid()
    {
        return $this->fromSeatid;
    }

    /**
     * Generated from protobuf field <code>uint32 fromSeatid = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setFromSeatid($var)
    {
        GPBUtil::checkUint32($var);
        $this->fromSeatid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 toSeatid = 3;</code>
     * @return int
     */
    public function getToSeatid()
    {
        return $this->toSeatid;
    }

    /**
     * Generated from protobuf field <code>uint32 toSeatid = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setToSeatid($var)
    {
        GPBUtil::checkUint32($var);
        $this->toSeatid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 areaid = 4;</code>
     * @return int
     */
    public function getAreaid()
    {
        return $this->areaid;
    }

    /**
     * Generated from protobuf field <code>uint32 areaid = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setAreaid($var)
    {
        GPBUtil::checkUint32($var);
        $this->areaid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 action = 5;</code>
     * @return int
     */
    public function getAction()
    {
        return $this->action;
    }

    /**
     * Generated from protobuf field <code>uint32 action = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setAction($var)
    {
        GPBUtil::checkUint32($var);
        $this->action = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 count = 6;</code>
     * @return int
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     * Generated from protobuf field <code>uint32 count = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 cards = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCards()
    {
        return $this->cards;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 cards = 7;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCards($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->cards = $arr;

        return $this;
    }

}

