<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/cotars_game_proto_card.proto

namespace Cotars\GameProtoCard;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Cotars.GameProtoCard.GameActionNty</code>
 */
class GameActionNty extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 tableid = 1;</code>
     */
    private $tableid = 0;
    /**
     * Generated from protobuf field <code>uint32 seatid = 2;</code>
     */
    private $seatid = 0;
    /**
     * Generated from protobuf field <code>uint32 timeout = 3;</code>
     */
    private $timeout = 0;
    /**
     * Generated from protobuf field <code>repeated .Cotars.GameProtoCard.GameAction actions = 4;</code>
     */
    private $actions;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $tableid
     *     @type int $seatid
     *     @type int $timeout
     *     @type \Cotars\GameProtoCard\GameAction[]|\Google\Protobuf\Internal\RepeatedField $actions
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\CotarsGameProtoCard::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 tableid = 1;</code>
     * @return int
     */
    public function getTableid()
    {
        return $this->tableid;
    }

    /**
     * Generated from protobuf field <code>uint32 tableid = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setTableid($var)
    {
        GPBUtil::checkUint32($var);
        $this->tableid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 seatid = 2;</code>
     * @return int
     */
    public function getSeatid()
    {
        return $this->seatid;
    }

    /**
     * Generated from protobuf field <code>uint32 seatid = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setSeatid($var)
    {
        GPBUtil::checkUint32($var);
        $this->seatid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 timeout = 3;</code>
     * @return int
     */
    public function getTimeout()
    {
        return $this->timeout;
    }

    /**
     * Generated from protobuf field <code>uint32 timeout = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setTimeout($var)
    {
        GPBUtil::checkUint32($var);
        $this->timeout = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Cotars.GameProtoCard.GameAction actions = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getActions()
    {
        return $this->actions;
    }

    /**
     * Generated from protobuf field <code>repeated .Cotars.GameProtoCard.GameAction actions = 4;</code>
     * @param \Cotars\GameProtoCard\GameAction[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setActions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Cotars\GameProtoCard\GameAction::class);
        $this->actions = $arr;

        return $this;
    }

}

