<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/cotars_game_proto_card.proto

namespace Cotars\GameProtoCard;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Cotars.GameProtoCard.GameInfoNtf</code>
 */
class GameInfoNtf extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .Cotars.GameProtoCard.GamePlayer players = 1;</code>
     */
    private $players;
    /**
     * Generated from protobuf field <code>uint32 lastSeatid = 2;</code>
     */
    private $lastSeatid = 0;
    /**
     * Generated from protobuf field <code>uint32 btnSeatid = 3;</code>
     */
    private $btnSeatid = 0;
    /**
     * Generated from protobuf field <code>uint32 leftCard = 4;</code>
     */
    private $leftCard = 0;
    /**
     * Generated from protobuf field <code>uint32 baseScore = 5;</code>
     */
    private $baseScore = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Cotars\GameProtoCard\GamePlayer[]|\Google\Protobuf\Internal\RepeatedField $players
     *     @type int $lastSeatid
     *     @type int $btnSeatid
     *     @type int $leftCard
     *     @type int $baseScore
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\CotarsGameProtoCard::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .Cotars.GameProtoCard.GamePlayer players = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPlayers()
    {
        return $this->players;
    }

    /**
     * Generated from protobuf field <code>repeated .Cotars.GameProtoCard.GamePlayer players = 1;</code>
     * @param \Cotars\GameProtoCard\GamePlayer[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPlayers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Cotars\GameProtoCard\GamePlayer::class);
        $this->players = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 lastSeatid = 2;</code>
     * @return int
     */
    public function getLastSeatid()
    {
        return $this->lastSeatid;
    }

    /**
     * Generated from protobuf field <code>uint32 lastSeatid = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setLastSeatid($var)
    {
        GPBUtil::checkUint32($var);
        $this->lastSeatid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 btnSeatid = 3;</code>
     * @return int
     */
    public function getBtnSeatid()
    {
        return $this->btnSeatid;
    }

    /**
     * Generated from protobuf field <code>uint32 btnSeatid = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setBtnSeatid($var)
    {
        GPBUtil::checkUint32($var);
        $this->btnSeatid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 leftCard = 4;</code>
     * @return int
     */
    public function getLeftCard()
    {
        return $this->leftCard;
    }

    /**
     * Generated from protobuf field <code>uint32 leftCard = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setLeftCard($var)
    {
        GPBUtil::checkUint32($var);
        $this->leftCard = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 baseScore = 5;</code>
     * @return int
     */
    public function getBaseScore()
    {
        return $this->baseScore;
    }

    /**
     * Generated from protobuf field <code>uint32 baseScore = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setBaseScore($var)
    {
        GPBUtil::checkUint32($var);
        $this->baseScore = $var;

        return $this;
    }

}

