<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/cotars_game_proto_card.proto

namespace Cotars\GameProtoCard;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Cotars.GameProtoCard.GamePlayer</code>
 */
class GamePlayer extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 uid = 1;</code>
     */
    private $uid = 0;
    /**
     * Generated from protobuf field <code>uint32 seatid = 2;</code>
     */
    private $seatid = 0;
    /**
     * Generated from protobuf field <code>repeated .Cotars.GameProtoCard.CardSet cardSets = 3;</code>
     */
    private $cardSets;
    /**
     * Generated from protobuf field <code>uint32 handCount = 4;</code>
     */
    private $handCount = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $uid
     *     @type int $seatid
     *     @type \Cotars\GameProtoCard\CardSet[]|\Google\Protobuf\Internal\RepeatedField $cardSets
     *     @type int $handCount
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\CotarsGameProtoCard::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 uid = 1;</code>
     * @return int
     */
    public function getUid()
    {
        return $this->uid;
    }

    /**
     * Generated from protobuf field <code>uint32 uid = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setUid($var)
    {
        GPBUtil::checkUint32($var);
        $this->uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 seatid = 2;</code>
     * @return int
     */
    public function getSeatid()
    {
        return $this->seatid;
    }

    /**
     * Generated from protobuf field <code>uint32 seatid = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setSeatid($var)
    {
        GPBUtil::checkUint32($var);
        $this->seatid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Cotars.GameProtoCard.CardSet cardSets = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCardSets()
    {
        return $this->cardSets;
    }

    /**
     * Generated from protobuf field <code>repeated .Cotars.GameProtoCard.CardSet cardSets = 3;</code>
     * @param \Cotars\GameProtoCard\CardSet[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCardSets($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Cotars\GameProtoCard\CardSet::class);
        $this->cardSets = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 handCount = 4;</code>
     * @return int
     */
    public function getHandCount()
    {
        return $this->handCount;
    }

    /**
     * Generated from protobuf field <code>uint32 handCount = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setHandCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->handCount = $var;

        return $this;
    }

}

