<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/cotars_game_proto_card.proto

namespace Cotars\GameProtoCard;

/**
 * Protobuf type <code>Cotars.GameProtoCard.MJCARD</code>
 */
class MJCARD
{
    /**
     * Generated from protobuf enum <code>MJCARD_NIL = 0;</code>
     */
    const MJCARD_NIL = 0;
    /**
     * Generated from protobuf enum <code>MJCARD_1_WANG = 1;</code>
     */
    const MJCARD_1_WANG = 1;
    /**
     * Generated from protobuf enum <code>MJCARD_2_WANG = 2;</code>
     */
    const MJCARD_2_WANG = 2;
    /**
     * Generated from protobuf enum <code>MJCARD_3_WANG = 3;</code>
     */
    const MJCARD_3_WANG = 3;
    /**
     * Generated from protobuf enum <code>MJCARD_4_WANG = 4;</code>
     */
    const MJCARD_4_WANG = 4;
    /**
     * Generated from protobuf enum <code>MJCARD_5_WANG = 5;</code>
     */
    const MJCARD_5_WANG = 5;
    /**
     * Generated from protobuf enum <code>MJCARD_6_WANG = 6;</code>
     */
    const MJCARD_6_WANG = 6;
    /**
     * Generated from protobuf enum <code>MJCARD_7_WANG = 7;</code>
     */
    const MJCARD_7_WANG = 7;
    /**
     * Generated from protobuf enum <code>MJCARD_8_WANG = 8;</code>
     */
    const MJCARD_8_WANG = 8;
    /**
     * Generated from protobuf enum <code>MJCARD_9_WANG = 9;</code>
     */
    const MJCARD_9_WANG = 9;
    /**
     * Generated from protobuf enum <code>MJCARD_1_TONG = 17;</code>
     */
    const MJCARD_1_TONG = 17;
    /**
     * Generated from protobuf enum <code>MJCARD_2_TONG = 18;</code>
     */
    const MJCARD_2_TONG = 18;
    /**
     * Generated from protobuf enum <code>MJCARD_3_TONG = 19;</code>
     */
    const MJCARD_3_TONG = 19;
    /**
     * Generated from protobuf enum <code>MJCARD_4_TONG = 20;</code>
     */
    const MJCARD_4_TONG = 20;
    /**
     * Generated from protobuf enum <code>MJCARD_5_TONG = 21;</code>
     */
    const MJCARD_5_TONG = 21;
    /**
     * Generated from protobuf enum <code>MJCARD_6_TONG = 22;</code>
     */
    const MJCARD_6_TONG = 22;
    /**
     * Generated from protobuf enum <code>MJCARD_7_TONG = 23;</code>
     */
    const MJCARD_7_TONG = 23;
    /**
     * Generated from protobuf enum <code>MJCARD_8_TONG = 24;</code>
     */
    const MJCARD_8_TONG = 24;
    /**
     * Generated from protobuf enum <code>MJCARD_9_TONG = 25;</code>
     */
    const MJCARD_9_TONG = 25;
    /**
     * Generated from protobuf enum <code>MJCARD_1_TIAO = 33;</code>
     */
    const MJCARD_1_TIAO = 33;
    /**
     * Generated from protobuf enum <code>MJCARD_2_TIAO = 34;</code>
     */
    const MJCARD_2_TIAO = 34;
    /**
     * Generated from protobuf enum <code>MJCARD_3_TIAO = 35;</code>
     */
    const MJCARD_3_TIAO = 35;
    /**
     * Generated from protobuf enum <code>MJCARD_4_TIAO = 36;</code>
     */
    const MJCARD_4_TIAO = 36;
    /**
     * Generated from protobuf enum <code>MJCARD_5_TIAO = 37;</code>
     */
    const MJCARD_5_TIAO = 37;
    /**
     * Generated from protobuf enum <code>MJCARD_6_TIAO = 38;</code>
     */
    const MJCARD_6_TIAO = 38;
    /**
     * Generated from protobuf enum <code>MJCARD_7_TIAO = 39;</code>
     */
    const MJCARD_7_TIAO = 39;
    /**
     * Generated from protobuf enum <code>MJCARD_8_TIAO = 40;</code>
     */
    const MJCARD_8_TIAO = 40;
    /**
     * Generated from protobuf enum <code>MJCARD_9_TIAO = 41;</code>
     */
    const MJCARD_9_TIAO = 41;
    /**
     * Generated from protobuf enum <code>MJCARD_DONG_FENG = 49;</code>
     */
    const MJCARD_DONG_FENG = 49;
    /**
     * Generated from protobuf enum <code>MJCARD_NAN_FENG = 50;</code>
     */
    const MJCARD_NAN_FENG = 50;
    /**
     * Generated from protobuf enum <code>MJCARD_XI_FENG = 51;</code>
     */
    const MJCARD_XI_FENG = 51;
    /**
     * Generated from protobuf enum <code>MJCARD_BEI_FENG = 52;</code>
     */
    const MJCARD_BEI_FENG = 52;
    /**
     * Generated from protobuf enum <code>MJCARD_ZHONG_JIAN = 65;</code>
     */
    const MJCARD_ZHONG_JIAN = 65;
    /**
     * Generated from protobuf enum <code>MJCARD_FA_JIAN = 66;</code>
     */
    const MJCARD_FA_JIAN = 66;
    /**
     * Generated from protobuf enum <code>MJCARD_BAI_JIAN = 67;</code>
     */
    const MJCARD_BAI_JIAN = 67;
    /**
     * Generated from protobuf enum <code>MJCARD_CHUN_HUA = 81;</code>
     */
    const MJCARD_CHUN_HUA = 81;
    /**
     * Generated from protobuf enum <code>MJCARD_XIA_HUA = 82;</code>
     */
    const MJCARD_XIA_HUA = 82;
    /**
     * Generated from protobuf enum <code>MJCARD_QIU_HUA = 83;</code>
     */
    const MJCARD_QIU_HUA = 83;
    /**
     * Generated from protobuf enum <code>MJCARD_DONG_HUA = 84;</code>
     */
    const MJCARD_DONG_HUA = 84;
    /**
     * Generated from protobuf enum <code>MJCARD_MEI_HUA = 85;</code>
     */
    const MJCARD_MEI_HUA = 85;
    /**
     * Generated from protobuf enum <code>MJCARD_LAN_HUA = 86;</code>
     */
    const MJCARD_LAN_HUA = 86;
    /**
     * Generated from protobuf enum <code>MJCARD_ZHU_HUA = 87;</code>
     */
    const MJCARD_ZHU_HUA = 87;
    /**
     * Generated from protobuf enum <code>MJCARD_JU_HUA = 88;</code>
     */
    const MJCARD_JU_HUA = 88;
}

