<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/cotars_game_proto_card.proto

namespace Cotars\GameProtoCard;

/**
 * Protobuf type <code>Cotars.GameProtoCard.MJCardType</code>
 */
class MJCardType
{
    /**
     * Generated from protobuf enum <code>MJCARD_TYPE_WANG = 0;</code>
     */
    const MJCARD_TYPE_WANG = 0;
    /**
     * Generated from protobuf enum <code>MJCARD_TYPE_TONG = 1;</code>
     */
    const MJCARD_TYPE_TONG = 1;
    /**
     * Generated from protobuf enum <code>MJCARD_TYPE_TIAO = 2;</code>
     */
    const MJCARD_TYPE_TIAO = 2;
    /**
     * Generated from protobuf enum <code>MJCARD_TYPE_FENG = 3;</code>
     */
    const MJCARD_TYPE_FENG = 3;
    /**
     * Generated from protobuf enum <code>MJCARD_TYPE_JIAN = 4;</code>
     */
    const MJCARD_TYPE_JIAN = 4;
    /**
     * Generated from protobuf enum <code>MJCARD_TYPE_HUA = 5;</code>
     */
    const MJCARD_TYPE_HUA = 5;
}

