<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/cotars_game_proto_card.proto

namespace Cotars\GameProtoCard;

/**
 * Protobuf type <code>Cotars.GameProtoCard.PlayerStatus</code>
 */
class PlayerStatus
{
    /**
     * Generated from protobuf enum <code>PLAYER_STATUS_IDLE = 0;</code>
     */
    const PLAYER_STATUS_IDLE = 0;
    /**
     * Generated from protobuf enum <code>PLAYER_STATUS_READY = 1;</code>
     */
    const PLAYER_STATUS_READY = 1;
    /**
     * Generated from protobuf enum <code>PLAYER_STATUS_START = 2;</code>
     */
    const PLAYER_STATUS_START = 2;
}

