<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/cotars_game_proto_card.proto

namespace Cotars\GameProtoCard;

/**
 * Protobuf type <code>Cotars.GameProtoCard.TableAction</code>
 */
class TableAction
{
    /**
     * Generated from protobuf enum <code>TABLE_ACTION_KEEP = 0;</code>
     */
    const TABLE_ACTION_KEEP = 0;
    /**
     * Generated from protobuf enum <code>TABLE_ACTION_SITDOWN = 1;</code>
     */
    const TABLE_ACTION_SITDOWN = 1;
    /**
     * Generated from protobuf enum <code>TABLE_ACTION_STANDUP = 2;</code>
     */
    const TABLE_ACTION_STANDUP = 2;
    /**
     * Generated from protobuf enum <code>TABLE_ACTION_READY = 3;</code>
     */
    const TABLE_ACTION_READY = 3;
    /**
     * Generated from protobuf enum <code>TABLE_ACTION_START = 4;</code>
     */
    const TABLE_ACTION_START = 4;
    /**
     * Generated from protobuf enum <code>TABLE_ACTION_LEAVE = 5;</code>
     */
    const TABLE_ACTION_LEAVE = 5;
    /**
     * Generated from protobuf enum <code>TABLE_ACTION_ENDVOTE = 6;</code>
     */
    const TABLE_ACTION_ENDVOTE = 6;
}

