<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/cotars_game_proto_card.proto

namespace Cotars\GameProtoCard;

/**
 * Protobuf type <code>Cotars.GameProtoCard.TableStatus</code>
 */
class TableStatus
{
    /**
     * Generated from protobuf enum <code>TABLE_STATUS_IDLE = 0;</code>
     */
    const TABLE_STATUS_IDLE = 0;
    /**
     * Generated from protobuf enum <code>TABLE_STATUS_WAIT = 1;</code>
     */
    const TABLE_STATUS_WAIT = 1;
    /**
     * Generated from protobuf enum <code>TABLE_STATUS_START = 2;</code>
     */
    const TABLE_STATUS_START = 2;
    /**
     * Generated from protobuf enum <code>TABLE_STATUS_END = 3;</code>
     */
    const TABLE_STATUS_END = 3;
}

